# Generated by Django 3.1 on 2024-04-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20240405_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
